### PR TITLE
PerformanceCounterUtility to use concurrent dictionary

### PR DESCRIPTION
**Pull request by MS-TimothyMothra**
#678

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
So what's the root cause of the issue? Why do we have a multiple threads trying to expand the names?

**Comment by cijothomas** [comment]
@SergeyKanzhelev - I believe we can go ahead and merge this, even if we don't know the exact scenario which caused multi-thread situation. Let me know otherwise.

**Comment by zvolkov** [comment]
Experiencing same issue here. When are you planning the next release to Nuget.org?

**Comment by cijothomas** [comment]
@zvolkov this fix will be in 2.5.0-beta1 which will be released very soon.. (1 week or so)

**Pull request merged**
