### PR TITLE
Merge develop into master for 2.4.0-beta4.

### PR DESCRIPTION
**Pull request by dnduffy**

### CODE REVIEW

**Comment by dnduffy** [comment]
@cijothomas Beta4 is basically replacing RC1 so we should take the fixes.

**Comment by cijothomas** [comment]
@dnduffy nope, beta4 is not rc1. There are pending things for rc1 which are yet to be in develop.

**Comment by dnduffy** [comment]
@cijothomas The current PR's say they are for 2.5.0-beta1, are you waiting for a PR that hasn't arrived yet?

**Comment by dnduffy** [comment]
@cijothomas Everything relevant to beta4 is merged/fixed that I know of and all the builds/tests are passing again.

**Comment by dnduffy** [comment]
After discussing with @SergeyKanzhelev and @Dmitry-Matveev we have decided to ship these changes in beta4 and merge tonight.  We can do additional testing and discuss in the morning if we want to push to NuGet or not.

**Pull request merged**
